ALTER TABLE Operadoras ALTER COLUMN cnpj TYPE VARCHAR(100);
ALTER TABLE PrimeiroT2023 
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);


ALTER TABLE SegundoT2023
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);

ALTER TABLE TerceiroT2023
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);


ALTER TABLE QuartoT2023
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);


ALTER TABLE PrimeiroT2024
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);

ALTER TABLE SegundoT2024
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);

ALTER TABLE TerceiroT2024
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);

ALTER TABLE QuartoT2024
ALTER COLUMN vl_inicial TYPE VARCHAR(20),
ALTER COLUMN vl_final TYPE VARCHAR(20),
ALTER COLUMN description TYPE VARCHAR(150);